short_name: example
namespace: local
version: 0.1.0
api_version: "0.1"
author: Maximilian Haye <m.haye@tu-berlin.de>
name:
  de: Beispiel
  en: Example
languages: [de, en]
build_hooks:
  pre: npm build
