/**
 * This file is part of the QuestionPy SDK. (https://questionpy.org)
 * The QuestionPy SDK is free software released under terms of the MIT license. See LICENSE.md.
 * (c) Technische Universität Berlin, innoCampus <info@isis.tu-berlin.de>
 */

import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { ESLint, type Rule } from 'eslint'
import { compile } from 'json-schema-to-typescript'
import prettier from 'prettier'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

const bannerComment = `/**
 * This file is part of the QuestionPy SDK. (https://questionpy.org)
 * The QuestionPy SDK is free software released under terms of the MIT license. See LICENSE.md.
 * (c) Technische Universität Berlin, innoCampus <info@isis.tu-berlin.de>
 */

// This file was automatically generated by generate-ts-types.py.
// DO NOT MODIFY IT BY HAND. Instead, modify the source Pydantic models, and regenerate this file.
`

async function readFromStdin(): Promise<string> {
    process.stdin.setEncoding('utf-8')
    let data = ''
    for await (const chunk of process.stdin) {
        data += chunk
    }
    return data
}

async function readPrettierConfig(): Promise<prettier.Options> {
    const config = await prettier.resolveConfig(path.resolve(__dirname, '.prettierrc.json'), { editorconfig: true })
    if (!config) {
        throw Error('Failed to load prettier config')
    }
    return config
}

async function fixCode(code: string): Promise<string> {
    const eslint = new ESLint({ fix: true, fixTypes: ['problem', 'suggestion', 'layout'] })
    const [result] = await eslint.lintText(code, { filePath: 'virtual.ts' })
    let fixedCode = result.output ?? code

    const applySuggestion = (source: string, fix: Rule.Fix) =>
        source.slice(0, fix.range[0]) + fix.text + source.slice(fix.range[1])

    for (const msg of result.messages) {
        const suggestion = msg.suggestions?.[0]
        if (suggestion) {
            fixedCode = applySuggestion(fixedCode, suggestion.fix)
        }
    }

    return fixedCode
}

async function main() {
    // Read JSON schema
    const jsonSchema = JSON.parse(await readFromStdin())

    const typeName = jsonSchema.title
    if (typeof typeName !== 'string') {
        throw new Error('Expected schema title')
    }

    // Generate TypeScript code
    const compiledCode = await compile(jsonSchema, typeName, {
        additionalProperties: false,
        bannerComment,
        format: false,
    })

    // Apply ESLint fixes and suggestions
    const fixedCode = await fixCode(compiledCode)

    // Format code
    const formattedCode = await prettier.format(fixedCode, {
        ...(await readPrettierConfig()),
        parser: 'typescript',
    })

    // Output
    process.stdout.write(formattedCode)
}

main().catch((error) => {
    console.error('Generation failed:', error)
    process.exit(1)
})
