/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'index': RouteRecordInfo<'index', '/', Record<never, never>, Record<never, never>>,
    'question': RouteRecordInfo<'question', '/question/:questionId', { questionId: ParamValue<true> }, { questionId: ParamValue<false> }>,
    'question-attempt': RouteRecordInfo<'question-attempt', '/question/:questionId/attempt/:attemptId', { questionId: ParamValue<true>, attemptId: ParamValue<true> }, { questionId: ParamValue<false>, attemptId: ParamValue<false> }>,
    'question-edit': RouteRecordInfo<'question-edit', '/question/:questionId/edit', { questionId: ParamValue<true> }, { questionId: ParamValue<false> }>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: 'index'
      views: never
    }
    'src/pages/question/[questionId]/index.vue': {
      routes: 'question'
      views: never
    }
    'src/pages/question/[questionId]/attempt/[attemptId].vue': {
      routes: 'question-attempt'
      views: never
    }
    'src/pages/question/[questionId]/edit.vue': {
      routes: 'question-edit'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
