short_name: static_files_example
namespace: local
version: 0.1.0
api_version: "0.1"
author: innoCampus <info@isis.tu-berlin.de>
name:
  de: Statische-Dateien-Beispiel
  en: Static files example
languages: [de, en]
