/**
 * This file is part of the QuestionPy SDK. (https://questionpy.org)
 * The QuestionPy SDK is free software released under terms of the MIT license. See LICENSE.md.
 * (c) Technische Universität Berlin, innoCampus <info@isis.tu-berlin.de>
 */

// This file was automatically generated by generate-ts-types.py.
// DO NOT MODIFY IT BY HAND. Instead, modify the source Pydantic models, and regenerate this file.

/**
 * Tuple of strings and ints identifying where in the schema the error occurred.
 */
export type Loc = (number | string)[]

/**
 * Represents a server-side error serialized for client display.
 */
export interface DetailedServerError {
    /**
     * The name of the exception.
     */
    error: string
    /**
     * Optional detailed error information, which may include a stack trace or Pydantic validation errors.
     */
    details?: string | ErrorDetails[] | null
}
export interface ErrorDetails {
    /**
     * The type of error that occurred, this is an identifier designed for
     * programmatic use that will change rarely or never.
     *
     * `type` is unique for each error message, and can hence be used as an identifier to build custom error messages.
     */
    type: string
    loc: Loc
    /**
     * A human readable error message.
     */
    msg: string
    /**
     * The input data at this `loc` that caused the error.
     */
    input: {
        [k: string]: unknown
    }
    ctx?: Ctx
    /**
     * The documentation URL giving information about the error. No URL is available if
     * a [`PydanticCustomError`][pydantic_core.PydanticCustomError] is used.
     */
    url?: string
}
/**
 * Values which are required to render the error message, and could hence be useful in rendering custom error messages.
 * Also useful for passing custom error data forward.
 */
export interface Ctx {
    [k: string]: unknown
}
