/*
 * This file is part of the QuestionPy SDK. (https://questionpy.org)
 * The QuestionPy SDK is free software released under terms of the MIT license. See LICENSE.md.
 * (c) Technische Universität Berlin, innoCampus <info@isis.tu-berlin.de>
 */

// This file was automatically generated by generate-ts-types.py.
// DO NOT MODIFY IT BY HAND. Instead, modify the source Pydantic models, and regenerate this file.

export type ErrorSectionKey = 'formulation' | 'general_feedback' | 'specific_feedback' | 'right_answer'
