/*
 * This file is part of the QuestionPy SDK. (https://questionpy.org)
 * The QuestionPy SDK is free software released under terms of the MIT license. See LICENSE.md.
 * (c) Technische Universität Berlin, innoCampus <info@isis.tu-berlin.de>
 */

// This file was automatically generated by generate-ts-types.py.
// DO NOT MODIFY IT BY HAND. Instead, modify the source Pydantic models, and regenerate this file.

export type ShortName = string
export type PackageType = 'LIBRARY' | 'QUESTIONTYPE' | 'QUESTION'
export type EnvironmentVariableName = string

/**
 * Represents a package manifest.
 *
 * Contains fields valid in a pre-built package manifest.
 */
export interface Manifest {
    short_name: ShortName
    namespace: string
    version: string
    api_version: string
    author: string
    name: Name
    entrypoint: string | null
    url: string | null
    /**
     * @minItems 1
     */
    languages: [string, ...string[]]
    description: Description
    icon: string | null
    type: PackageType
    license: string | null
    permissions: PartialPackagePermissions | null
    environment_variables: EnvironmentVariableName[] | null
    tags: string[]
    requirements: string | string[] | null
    static_files: StaticFiles
    dependencies: DistDependencies
    state_version: number
    possible_side_migrations: PossibleSideMigrations
}
export interface Name {
    [k: string]: string
}
export interface Description {
    [k: string]: string
}
export interface PartialPackagePermissions {
    cpus: number | null
    memory: number | null
    request_timeout: number | null
    bootstrap_timeout: number | null
    main_process_execution_modes: [string, ...string[]] | null
    lms_attributes: string[] | null
}
export interface StaticFiles {
    [k: string]: PackageFile
}
/**
 * Represents a static file included in a built package.
 */
export interface PackageFile {
    mime_type: string | null
    size: number
}
export interface DistDependencies {
    qpy: DistStaticQPyDependency[]
}
export interface DistStaticQPyDependency {
    dir_name: string
    hash: string
}
export interface PossibleSideMigrations {
    [k: string]: {
        [k: string]: number[]
    }
}
