/*
 * This file is part of the QuestionPy SDK. (https://questionpy.org)
 * The QuestionPy SDK is free software released under terms of the MIT license. See LICENSE.md.
 * (c) Technische Universität Berlin, innoCampus <info@isis.tu-berlin.de>
 */

// This file was automatically generated by generate-ts-types.py.
// DO NOT MODIFY IT BY HAND. Instead, modify the source Pydantic models, and regenerate this file.

export type PackageType = 'LIBRARY' | 'QUESTIONTYPE' | 'QUESTION'
export type EnvironmentVariableName = string
export type DistQPyDependency = DistStaticQPyDependency | DistDynamicQPyDependency
export type Version = string | null
export type DependencyLockStrategy = 'required' | 'preferred-no-downgrade' | 'preferred-allow-downgrade'
export type Qpy = DistQPyDependency[]

/**
 * Represents a package manifest.
 *
 * Contains fields valid in a pre-built package manifest.
 */
export interface Manifest {
    short_name: string
    namespace: string
    version: string
    api_version: string
    author: string
    name: Name
    entrypoint: string | null
    url: string | null
    /**
     * @minItems 1
     */
    languages: [string, ...string[]]
    description: Description
    icon: string | null
    type: PackageType
    license: string | null
    permissions: PartialPackagePermissions | null
    environment_variables: EnvironmentVariableName[] | null
    tags: string[]
    requirements: string | string[] | null
    static_files: StaticFiles
    dependencies: DistDependencies
}
export interface Name {
    [k: string]: string
}
export interface Description {
    [k: string]: string
}
export interface PartialPackagePermissions {
    cpus: number | null
    memory: number | null
    request_timeout: number | null
    bootstrap_timeout: number | null
    main_process_execution_modes: [string, ...string[]] | null
    lms_attributes: string[] | null
}
export interface StaticFiles {
    [k: string]: PackageFile
}
/**
 * Represents a static file included in a built package.
 */
export interface PackageFile {
    mime_type: string | null
    size: number
}
export interface DistDependencies {
    qpy: Qpy
}
export interface DistStaticQPyDependency {
    namespace: string
    short_name: string
    version: string
    dependencies: DistDependencies1
    hash: string
}
export interface DistDependencies1 {
    qpy: Qpy
}
export interface DistDynamicQPyDependency {
    namespace: string
    short_name: string
    version: Version
    include_prereleases: boolean
    locked: LockedDependencyInfo | null
}
export interface LockedDependencyInfo {
    strategy: DependencyLockStrategy
    locked_version: string
    locked_hash: string
}
