/*
 * This file is part of the QuestionPy SDK. (https://questionpy.org)
 * The QuestionPy SDK is free software released under terms of the MIT license. See LICENSE.md.
 * (c) Technische Universität Berlin, innoCampus <info@isis.tu-berlin.de>
 */

// This file was automatically generated by generate-ts-types.py.
// DO NOT MODIFY IT BY HAND. Instead, modify the source Pydantic models, and regenerate this file.

export type OptionsFormValue = OptionsFormBaseValue | OptionsFormModelValue | OptionsFormModelValue[]
export type OptionsFormBaseValue = string | number | boolean | string[] | OptionsFile[] | RichTextEditor | null

/**
 * Represents the API response data for the question's options state.
 */
export interface OptionsStateResponse {
    data: OptionsFormData
    /**
     * Whether the question is newly created and has not been persisted yet.
     */
    is_new: boolean
}
/**
 * The question's options form data.
 */
export interface OptionsFormData {
    [k: string]: OptionsFormValue
}
/**
 * Metadata about a file uploaded in question options.
 *
 * The file content is stored by the LMS and can be retrieved using the
 * [`file_ref`][questionpy.form.OptionsFile.file_ref] or embedded in the question using
 * [`uri`][questionpy.form.OptionsFile.uri]. The filename can be freely changed without informing the LMS.
 *
 * See Also:
 *     - [questionpy.form.rich_text_editor][]
 *     - [questionpy.form.file_upload][]
 */
export interface OptionsFile {
    path: string
    filename: string
    file_ref: string
    uploaded_at: string
    mime_type: string
    size: number
}
/**
 * The form data generated by a [questionpy.form.rich_text_editor][] element.
 */
export interface RichTextEditor {
    text: string
    files: OptionsFile[]
    [k: string]: unknown
}
export interface OptionsFormModelValue {
    [k: string]: OptionsFormValue
}
