/*
 * This file is part of the QuestionPy SDK. (https://questionpy.org)
 * The QuestionPy SDK is free software released under terms of the MIT license. See LICENSE.md.
 * (c) Technische Universität Berlin, innoCampus <info@isis.tu-berlin.de>
 */

// This file was automatically generated by generate-ts-types.py.
// DO NOT MODIFY IT BY HAND. Instead, modify the source Pydantic models, and regenerate this file.

export type FormElement = LeafFormElement | ContainerFormElement
export type LeafFormElement =
    | CheckboxElement
    | HiddenElement
    | GeneratedIdElement
    | SelectElement
    | StaticTextElement
    | TextInputElement
    | TextAreaElement
export type Condition = IsChecked | IsNotChecked | Equals | DoesNotEqual | In
export type ContainerFormElement = GroupElement | RadioGroupElement | RepetitionElement
export type Elements = (LeafFormElement | RadioGroupElement | GroupElement)[]

export interface OptionsFormDefinition {
    general: FormElement[]
    sections: FormSection[]
}
export interface CheckboxElement {
    help: string | null
    disable_if: Condition[]
    hide_if: Condition[]
    kind: 'checkbox'
    name: string
    left_label: string | null
    right_label: string | null
    required: boolean
    selected: boolean
}
export interface IsChecked {
    kind: 'is_checked'
    name: string
}
export interface IsNotChecked {
    kind: 'is_not_checked'
    name: string
}
export interface Equals {
    kind: 'equals'
    name: string
    value: string | number | boolean
}
export interface DoesNotEqual {
    kind: 'does_not_equal'
    name: string
    value: string | number | boolean
}
export interface In {
    kind: 'in'
    name: string
    value: (string | number | boolean)[]
}
/**
 * An element that isn't shown to the user but still submits its fixed value.
 */
export interface HiddenElement {
    disable_if: Condition[]
    hide_if: Condition[]
    kind: 'hidden'
    name: string
    value: string
}
/**
 * Generates a unique ID which won't change across form saves.
 *
 * Useful to distinguish repetitions without relying on their index, which may change when repetitions are removed.
 */
export interface GeneratedIdElement {
    kind: 'id'
    name: string
}
/**
 * A drop-down list.
 */
export interface SelectElement {
    help: string | null
    disable_if: Condition[]
    hide_if: Condition[]
    label: string
    kind: 'select'
    name: string
    multiple: boolean
    options: Option[]
    required: boolean
}
/**
 * A possible option for radio groups and drop-downs.
 */
export interface Option {
    label: string
    value: string
    selected: boolean
}
/**
 * Some static text with a label.
 */
export interface StaticTextElement {
    help: string | null
    disable_if: Condition[]
    hide_if: Condition[]
    label: string
    kind: 'static_text'
    name: string
    text: string
}
export interface TextInputElement {
    help: string | null
    disable_if: Condition[]
    hide_if: Condition[]
    label: string
    kind: 'input'
    name: string
    required: boolean
    default: string | null
    placeholder: string | null
}
export interface TextAreaElement {
    help: string | null
    disable_if: Condition[]
    hide_if: Condition[]
    label: string
    kind: 'textarea'
    name: string
    required: boolean
    default: string | null
    placeholder: string | null
}
/**
 * Groups multiple elements horizontally with a common label.
 */
export interface GroupElement {
    help: string | null
    disable_if: Condition[]
    hide_if: Condition[]
    label: string
    kind: 'group'
    name: string
    elements: LeafFormElement[]
}
/**
 * Group of radio buttons, of which at most one can be selected at a time.
 */
export interface RadioGroupElement {
    help: string | null
    disable_if: Condition[]
    hide_if: Condition[]
    label: string
    kind: 'radio_group'
    name: string
    options: Option[]
    required: boolean
}
/**
 * Repeats a number of elements, allowing the user to add new repetitions with the click of a button.
 */
export interface RepetitionElement {
    kind: 'repetition'
    name: string
    initial_repetitions: number
    minimum_repetitions: number
    increment: number
    button_label: string | null
    elements: Elements
}
/**
 * Form section that can be expanded and collapsed.
 */
export interface FormSection {
    name: string
    header: string
    elements: FormElement[]
}
