[pytest]
addopts = --browser chromium --tracing=retain-on-failure --output=e2e-results
asyncio_mode = auto
# https://playwright.dev/python/docs/test-runners#async-fixtures
asyncio_default_test_loop_scope = session
asyncio_default_fixture_loop_scope = session
norecursedirs = "tests"
