#  This file is part of the QuestionPy SDK. (https://questionpy.org)
#  The QuestionPy SDK is free software released under terms of the MIT license. See LICENSE.md.
#  (c) Technische Universität Berlin, innoCampus <info@isis.tu-berlin.de>
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from itertools import starmap
from typing import TYPE_CHECKING, Annotated, Any, ClassVar, Generic, Literal, NewType, get_args, get_origin

from pydantic import BaseModel, Field, model_validator
from pydantic._internal._model_construction import ModelMetaclass  # noqa: PLC2701
from pydantic.fields import FieldInfo
from pydantic_core import CoreSchema, core_schema
from typing_extensions import TypeVar

from questionpy_common import TranslatableString
from questionpy_common.elements import FormElement, FormSection, OptionsFormDefinition


class OptionsFile(BaseModel):
    """Metadata about a file uploaded in question options.

    The file content is stored by the LMS and can be retrieved using the
    [`file_ref`][questionpy.form.OptionsFile.file_ref] or embedded in the question using
    [`uri`][questionpy.form.OptionsFile.uri]. The filename can be freely changed without informing the LMS.

    See Also:
        - [questionpy.form.rich_text_editor][]
        - [questionpy.form.file_upload][]
    """

    filename: str
    file_ref: str
    """An opaque reference that can be used to retrieve the file content from the LMS."""
    uploaded_at: datetime
    mime_type: str

    @property
    def uri(self) -> str:
        """Builds a URI that can be used to embed the file in a question."""
        return f"qpy://options/{self.file_ref}"


WithHtml = NewType("WithHtml", str)
"""Used in [RichTextEditor][] make `html` required."""
# TypeVar defaults are only introduced in Python 3.13, hence typing_extensions.TypeVar.
_HtmlT = TypeVar("_HtmlT", WithHtml, WithHtml | None, default=WithHtml | None)


class RichTextEditor(BaseModel, Generic[_HtmlT]):
    """The form data generated by a [questionpy.form.rich_text_editor][] element.

    For type-safety, `RichTextEditor[WithHtml]` will make the `html` field required when `include_html=True` is used.
    """

    markup: str
    markup_format: str
    """Known values: `html`, `markdown` and `plain`."""
    html: Annotated[_HtmlT, Field(default=None, validate_default=True)]
    """If included, the HTML rendered from the markup.

    Required if [questionpy.form.rich_text_editor][](include_html=True) is used.

    If the markup format is already HTML, `markup` and `html` should contain the same text. When validating, `html` can
    be omitted and will be inferred from `markup`.
    """
    files: list[OptionsFile] = []
    """Files referenced by the markup."""

    @model_validator(mode="before")
    @classmethod
    def __infer_html(cls, data: object) -> object:
        """When the markup format is HTML, set `markup` from `html` and vice versa."""
        if (
            isinstance(data, Mapping)
            and data.get("markup_format") == "html"
            and data.get("markup") is not None
            and data.get("html") is None
        ):
            return {**data, "html": data["markup"]}
        return data


@dataclass
class _OptionInfo:
    label: str | TranslatableString
    selected: bool
    value: str | None = None
    """If None, set to the name by `OptionEnum.__init__` because __set_name__ doesn't get called for enum members."""


class OptionEnum(Enum):
    """Enum specifying the possible options for radio groups and drop-downs.

    Specify options using [`option`][questionpy.form.option].
    """

    def __init__(self, option: _OptionInfo) -> None:
        super().__init__()
        if option.value is None:
            option.value = self.name

        self._value_ = option.value
        self.label = option.label
        self.selected = option.selected

    @classmethod
    def __get_pydantic_core_schema__(cls, *_: object) -> CoreSchema:
        # Configure Pydantic to validate us from and serialize us to strings.
        # This doesn't change the behaviour of json.dump or json.load, but that's probably ok.

        def validate(value: Any) -> "OptionEnum":
            if isinstance(value, cls):
                return value

            if isinstance(value, str):
                try:
                    return cls[value]
                except KeyError as e:
                    msg = f"Not a valid {cls.__name__} value: '{value}'"
                    raise ValueError(msg) from e

            msg = f"str or {cls.__name__} required, got '{value}'"
            raise TypeError(msg)

        def serialize(enum_member: "OptionEnum") -> str:
            return enum_member.value

        return core_schema.no_info_plain_validator_function(
            validate, serialization=core_schema.plain_serializer_function_ser_schema(serialize)
        )


@dataclass
class _FieldInfo:
    type: object
    """The type of the field."""
    build: Callable[[str], FormElement]
    """We want to use the name of the model field as the name of the form element, but that isn't known when the dsl
    functions are called. So they provide a callable instead that takes the name and returns the complete form element.
    """
    pydantic_field_info: FieldInfo | None = None
    annotate_with: Sequence[object] = ()
    """Annotations as in [typing.Annotated][] to add to the field type. Useful for [pydantic.BeforeValidator][]."""


@dataclass
class _StaticElementInfo:
    build: Callable[[str], FormElement]


@dataclass
class _SectionInfo:
    header: str | TranslatableString
    model: type["FormModel"]


def _is_valid_annotation(annotation: object, expected: object) -> bool:
    """Checks if `annotation` is valid for a form element that produces values of type `expected`."""
    # TODO: pydantic is able to coerce many input values, such as strings to floats, so better logic may be
    #       needed here

    if annotation == expected or annotation is Any:
        return True

    expected_origin = get_origin(expected)
    expected_args = get_args(expected)

    annotation_origin = get_origin(annotation)
    annotation_args = get_args(annotation)

    if expected_origin is Literal and isinstance(annotation, type):
        # An annotation t and an expected type Literal[x] are valid if x is an instance of t
        # (Example: bool and Literal[True])
        return isinstance(expected_args[0], annotation)

    if expected_origin and expected_origin is annotation_origin:
        # For an arbitrary generic G and an expected type G[x],
        # an annotation G[y] is valid if _is_valid_annotation(x, y) (recursively)
        return len(expected_args) == len(annotation_args) and all(
            starmap(_is_valid_annotation, zip(annotation_args, expected_args, strict=False))
        )

    return False


class _FormModelMeta(ModelMetaclass):
    if TYPE_CHECKING:
        # this is set by ModelMetaclass, but mypy doesn't know
        model_fields: dict[str, FieldInfo]

    __slots__ = ()

    def __new__(mcs, name: str, bases: tuple[type, ...], namespace: dict, **kwargs: Any) -> type:
        annotations = namespace.get("__annotations__", {}).copy()
        new_namespace: dict[str, Any] = {}
        form = OptionsFormDefinition()

        for key, value in namespace.items():
            annotate_with: list[object] = []
            if isinstance(value, _FieldInfo):
                expected_type = value.type
                form.general.append(value.build(key))
                if value.pydantic_field_info is not None:
                    new_namespace[key] = value.pydantic_field_info
                if value.annotate_with:
                    annotate_with.extend(value.annotate_with)
            elif isinstance(value, _SectionInfo):
                form.sections.append(FormSection(name=key, header=value.header, elements=value.model.qpy_form.general))
                expected_type = value.model
                new_namespace[key] = Field(default={}, validate_default=True)
            elif isinstance(value, _StaticElementInfo):
                element = value.build(key)
                form.general.append(element)
                expected_type = type(element)
                new_namespace[key] = Field(default=element, frozen=True, exclude=True)
            else:
                # not one of our special types, use as is
                new_namespace[key] = value
                continue

            if key in annotations:
                # explicit type defined, check its validity
                if not _is_valid_annotation(annotations[key], expected_type):
                    msg = (
                        f"The element '{key}' produces values of type '{expected_type}', but is annotated "
                        f"with '{annotations[key]}'"
                    )
                    raise TypeError(msg)
            else:
                # no explicit type defined, set the default
                # this won't help type checkers or code completion, but will allow pydantic to validate inputs
                annotations[key] = expected_type

            if annotate_with:
                # If the field type has been annotated by the user, this will add our annotations to theirs.
                annotations[key] = Annotated[annotations[key], *annotate_with]

        new_namespace["__annotations__"] = annotations
        cls: _FormModelMeta = super().__new__(mcs, name, bases, new_namespace, **kwargs)  # type: ignore[assignment]
        cls.__qpy_form = form
        return cls

    __qpy_form: OptionsFormDefinition

    def __getattr__(cls, key: str) -> object:  # noqa: N805 (cls is the convention in metaclasses)
        # Properties do not seem to work correctly in metaclasses.
        if key == "qpy_form":
            # We copy the form every time it is accessed to prevent changes (such as adding an extra element) from
            # snowballing from request to request.
            return cls.__qpy_form.model_copy(deep=True)
        raise AttributeError(key, name=key, obj=cls)


class FormModel(BaseModel, metaclass=_FormModelMeta):
    """Declarative form definition.

    Use the DSL functions to define your elements as fields, and have submitted form data automatically validated into a
    type-safe instance of your model.
    """

    __slots__ = ()

    qpy_form: ClassVar[OptionsFormDefinition]
    """The form defined by this declarative model."""
