name: "CI"

on:
  push:
  pull_request:
    # We don't run on PR synchronize, because that would duplicate the push-Build
    types:
      - opened

jobs:
  python:
    uses: questionpy-org/.github/.github/workflows/python-ci.yml@v10
    with:
      # GitHub workflow inputs do not support lists, so we pass JSON.
      pytest-python-versions: '["3.12", "3.13"]'
      packages: questionpy questionpy_sdk tests

  node:
    uses: questionpy-org/.github/.github/workflows/node-ci.yml@v10
    with:
      node-version: "22"
      prefix: frontend

  e2e-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_IN_PROJECT: true
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - uses: questionpy-org/actions-setup/setup-python@v1
        with:
          python-version: "3.13"
          poetry-options: --with test

      - name: Install Chromium
        run: poetry run --no-interaction -- playwright install chromium

      - name: Run E2E tests
        run: poetry run --no-interaction -- ./run_e2e_tests.sh

      - name: Upload traces
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() && hashFiles('e2e-results/**') }}
        with:
          name: playwright-traces
          path: e2e-results/
