name: Node.js Checks
on: workflow_call

jobs:
  format-check:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: ./.github/actions/setup-node
      - name: Check formatting
        run: npm run format-check --prefix frontend

  lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: ./.github/actions/setup-node
      - name: Lint
        run: npm run lint --prefix frontend

  type-check:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: ./.github/actions/setup-node
      - name: Type check
        run: npm run type-check --prefix frontend

  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: ./.github/actions/setup-node
      - name: Run tests
        run: npm run test --prefix frontend
